import type { Details } from './common'

export interface ZitadelUserAuthenticationMethodsGetResponse {
  details: Details
  authMethodTypes: AuthMethodTypes[]
}

export enum AuthMethodTypes {
  UNSPECIFIED = 'AUTHENTICATION_METHOD_TYPE_UNSPECIFIED',
  PASSWORD = 'AUTHENTICATION_METHOD_TYPE_PASSWORD',
  PASSKEY = 'AUTHENTICATION_METHOD_TYPE_PASSKEY',
  IDP = 'AUTHENTICATION_METHOD_TYPE_IDP',
  TOTP = 'AUTHENTICATION_METHOD_TYPE_TOTP',
  U2F = 'AUTHENTICATION_METHOD_TYPE_U2F',
  SMS = 'AUTHENTICATION_METHOD_TYPE_OTP_SMS',
  EMAIL = 'AUTHENTICATION_METHOD_TYPE_OTP_EMAIL',
}
