name: Release

permissions:
  id-token: write
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZITADEL_INSTANCE_URL: ${{ secrets.ZITADEL_INSTANCE_URL }}
          ZITADEL_KEY_FILE_PATH: ${{ secrets.ZITADEL_KEY_FILE_PATH }}
          ZITADEL_APP_OIDC_REDIRECT_URI: ${{ secrets.ZITADEL_APP_OIDC_REDIRECT_URI }}

      # # Uncomment the following lines to publish to npm on CI
      #
      - run: pnpm install
      - run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
